# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the New Relic Java Agent"
  homepage = "https://github.com/ktronkowski"
  id = "paketo-buildpacks/newrelic-java-agent"
  keywords = ["java", "new-relic"]
  name = "Paketo Java Application New Relic Agent Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
#  version = "{{.version}}"
  version = "1.0.0"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/ktronkowski/new-relic-agent/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/helper", "bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:newrelic:java-agent:7.4.3:*:*:*:*:*:*:*"]
    id = "newrelic-java-agent"
    name = "New Relic Java Agent"
    purl = "pkg:generic/newrelic-java-agent@7.4.3"
    sha256 = "232eda66caa1bea248de8c6dbf22af5b0e070b4d3b61b66569fe3b5515698bfa"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://download.newrelic.com/newrelic/java-agent/newrelic-agent/7.4.3/newrelic-agent-7.4.3.jar"
    version = "7.4.3"

    [[metadata.dependencies.licenses]]
      type = "Apache"
      uri = "https://github.com/newrelic/newrelic-java-agent/blob/main/LICENSE"


[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
